### ISSUE TITLE
Check server rewrite permissions in the web installer

### ISSUE THREAD

**Issue by digininja** [octobercms/install#104]
- OctoberCMS Build: whatever the latest is from the automatic installer
- PHP Version: 7.2
- Database Engine: mariadb
- Plugins Installed: None

### Description:
The wizard installer doesn't check that mod_rewrite is installed so after the install has finished AJAX framework demo in here fails as you are walking through the first pages of the newly installed site

`/demo/ajax`

I assume the rest of the site also doesn't work but I fixed it before I tried.

It also doesn't check that htaccess is allowed to contain all the things it does. Mine wasn't and so various pages broke till I gave it permissions.

I can understand the CLI version missing things like this, but the wizard version is selling itself as a hands off installer which it isn't in this situation.

### Steps To Reproduce:

Install the app without mod_rewrite enabled and with no permission for htaccess to override anything.

**Comment by daftspunk** [comment]
ModRewrite is a common module and should be enabled for almost all web applications that use a `.htaccess` file. 

Not sure if it is within the scope of an installer to check this. It's a cool idea to check for it programmatically but instead, we should just add it to the documentation as a server requirement for Apache, specifically

Thanks!
