### ISSUE TITLE
The following config files are not getting created by the installer

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/install#112]
See screenshot:

![image](https://user-images.githubusercontent.com/57409060/92308640-07e88300-ef97-11ea-98e8-4ed568378832.png)

The following config files are not being installed:

- `develop.php` - I opened an issue for this somewhere else. Github issue (closed) https://github.com/octobercms/october/issues/4864

- `hashing.php` - first time issue has been raised.

- `logging.php` - first time issue has been raised.

p.s. `master` branch seems to have been deleted, so I can only compare to `develop` branch against the installer now.

**Comment by LukeTowers** [comment]
Those files are in the 1.1 branch of October (the L6 update), not in a stable build yet so they wouldn't be installed by the installer yet.
