### ISSUE TITLE
Allow a toggle function to view the password fields and switch between seeing and hiding the form field values

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/install#113]
See screenshot:

![image](https://user-images.githubusercontent.com/57409060/105393037-ce49a900-5c13-11eb-9881-6973daa910b6.png)

**Comment by LukeTowers** [comment]
Look at the sensitive form widget in the backend module to get an idea of how you could implement that in a PR.

**Comment by ayumi-cloud** [comment]
https://github.com/octobercms/docs/blob/628a2e48f7da2ada0de45b55a79f97407f1a96f5/backend-forms.md#sensitive

**Comment by ayumi-cloud** [comment]
https://github.com/octobercms/docs/blob/master/backend-forms.md#sensitive

**Comment by ayumi-cloud** [comment]
Looked at the code, I don't like it (sorry). Going to code my own (lightweight) version.

**Comment by ayumi-cloud** [comment]
![image](https://user-images.githubusercontent.com/57409060/105513595-6bffaf80-5cca-11eb-8b58-f7a0ec0c3ca7.png)
