### ISSUE TITLE
All vendor files are way out of date

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/install#115]
@LukeTowers 

Some of the vendor files have a ton of security vulnerabilities.

I see many security issues in the partial files as well.

I don't have time to fix them, no offence but I'm wasting way too much time doing many pr's for you guys. I really need to get on with my work.

**Comment by LukeTowers** [comment]
> I don't have time to fix them, no offence but I'm wasting way too much time doing many pr's for you guys. I really need to get on with my work.

No offence but I'm wasting way too much time supporting you for free, I really need to get on with my work.

😛

**Comment by ayumi-cloud** [comment]
No problem if you cant be bothered - I just delete all my pr's in october.

**Comment by LukeTowers** [comment]
@ayumi-cloud that's your call. Less of a workload for us to deal with now.
