### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by Eeesbk** [octobercms/install#122]
{
  "message": "Class \"Composer\\Util\\Http\\ProxyHelper\" not found",
  "exception": "Error",
  "file": "/public_html/vendor/composer/composer/src/Composer/Util/Http/ProxyManager.php",
  "line": 131,
  "trace": [
    {
      "file": "/public_html/vendor/composer/composer/src/Composer/Util/Http/ProxyManager.php",
      "line": 55,
      "function": "initProxyData",
      "class": "Composer\\Util\\Http\\ProxyManager",
      "type": "->"
    },
    {
      "file": "/public_html/vendor/composer/composer/src/Composer/Util/Http/ProxyManager.php",
      "line": 61,
      "function": "__construct",
      "class": "Composer\\Util\\Http\\ProxyManager",
      "type": "->"
    },
    {
      "file": "/public_html/vendor/composer/composer/src/Composer/Util/Http/CurlDownloader.php",
      "line": 119,
      "function": "getInstance",
      "class": "Composer\\Util\\Http\\ProxyManager",
      "type": "::"
    },
    {
      "file": "/public_html/vendor/composer/composer/src/Composer/Util/HttpDownloader.php",
      "line": 86,
      "function": "__construct",
      "class": "Composer\\Util\\Http\\CurlDownloader",
      "type": "->"
    },
    {
      "file": "/public_html/vendor/composer/composer/src/Composer/Factory.php",
      "line": 668,
      "function": "__construct",
      "class": "Composer\\Util\\HttpDownloader",
      "type": "->"
    },
    {
      "file": "/public_html/vendor/composer/composer/src/Composer/Factory.php",
      "line": 365,
      "function": "createHttpDownloader",
      "class": "Composer\\Factory",
      "type": "::"
    },
    {
      "file": "/public_html/vendor/composer/composer/src/Composer/Factory.php",
      "line": 629,
      "function": "createComposer",
      "class": "Composer\\Factory",
      "type": "->"
    },
    {
      "file": "/public_html/vendor/october/rain/src/Composer/Manager.php",
      "line": 284,
      "function": "create",
      "class": "Composer\\Factory",
      "type": "::"
    },
    {
      "file": "/public_html/vendor/october/rain/src/Composer/Manager.php",
      "line": 80,
      "function": "makeComposer",
      "class": "October\\Rain\\Composer\\Manager",
      "type": "->"
    },
    {
      "file": "/public_html/install_files/php/Installer.php",
      "line": 218,
      "function": "require",
      "class": "October\\Rain\\Composer\\Manager",
      "type": "->"
    },
    {
      "file": "/public_html/install_files/php/InstallerHandlers.php",
      "line": 187,
      "function": "runComposerInstall",
      "class": "Installer",
      "type": "->"
    },
    {
      "file": "/public_html/install_files/php/Installer.php",
      "line": 47,
      "function": "onInstallStep",
      "class": "Installer",
      "type": "->"
    },
    {
      "file": "/public_html/install_files/php/boot.php",
      "line": 87,
      "function": "__construct",
      "class": "Installer",
      "type": "->"
    },
    {
      "file": "/public_html/install.php",
      "line": 1,
      "function": "include"
    }
  ]
}

**Comment by daftspunk** [comment]
I confirmed the installer is currently functional.

![image](https://github.com/octobercms/install/assets/1392869/c4ec3b50-8bfb-4852-83fe-5b0e4d8518b3)

You may need to provide more details about your environment. Operating system, PHP version, etc.

**Comment by Eeesbk** [comment]
Hosting sprinthost.ru PHP 8.0 / 8.3

**Comment by daftspunk** [comment]
Does it happen with both PHP 8.0 and PHP 8.3?

**Comment by Eeesbk** [comment]
ДА

**Comment by daftspunk** [comment]
Please contact the helpdesk about this issue. Here is the link: https://octobercms.com/contact
