### ISSUE TITLE
Issue with install wizard on multiple servers

### ISSUE THREAD

**Issue by david-adante** [octobercms/install#123]
Hello, 
I tried to install newest Octobercms via install wizard. 
After some time I get the error:
I tried this on two servers but with same result. Localy also. 

![image](https://github.com/user-attachments/assets/5801b5d8-811b-4dcd-a492-b68043a66be7)

In the install.log there is stacktrace:

`[2024/09/10 06:06:16] Handler error (onInstallStep): file_get_contents(/var/www/html/vendor/composer/composer/src/Composer/Repository/../InstalledVersions.php): Failed to open stream: No such file or directory
[2024/09/10 06:06:16] Array
(
    [0] => Trace log:
    [1] => #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_get_conten...', '/var/www/html/v...', 166)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(2, 'file_get_conten...', '/var/www/html/v...', 166)
#2 /var/www/html/vendor/composer/composer/src/Composer/Repository/FilesystemRepository.php(166): file_get_contents('/var/www/html/v...')
#3 /var/www/html/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(381): Composer\Repository\FilesystemRepository->write(true, Object(Composer\Installer\InstallationManager))
#4 /var/www/html/vendor/react/promise/src/Internal/FulfilledPromise.php(47): Composer\Installer\InstallationManager->Composer\Installer\{closure}(NULL)
#5 /var/www/html/vendor/react/promise/src/Promise.php(173): React\Promise\Internal\FulfilledPromise->then(Object(Closure), Object(Closure))
#6 /var/www/html/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\Internal\FulfilledPromise))
#7 /var/www/html/vendor/react/promise/src/Promise.php(286): React\Promise\Promise->settle(Object(React\Promise\Internal\FulfilledPromise))
#8 /var/www/html/vendor/react/promise/src/Internal/FulfilledPromise.php(47): React\Promise\Promise::React\Promise\{closure}(NULL)
#9 /var/www/html/vendor/react/promise/src/Promise.php(180): React\Promise\Internal\FulfilledPromise->then(Object(Closure), Object(Closure))
#10 /var/www/html/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\Internal\FulfilledPromise))
#11 /var/www/html/vendor/react/promise/src/Promise.php(286): React\Promise\Promise->settle(Object(React\Promise\Internal\FulfilledPromise))
#12 /var/www/html/vendor/react/promise/src/Internal/FulfilledPromise.php(47): React\Promise\Promise::React\Promise\{closure}(NULL)
#13 /var/www/html/vendor/react/promise/src/Promise.php(180): React\Promise\Internal\FulfilledPromise->then(Object(Closure), Object(Closure))
#14 /var/www/html/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\Internal\FulfilledPromise))
#15 /var/www/html/vendor/react/promise/src/Promise.php(286): React\Promise\Promise->settle(Object(React\Promise\Internal\FulfilledPromise))
#16 /var/www/html/vendor/react/promise/src/Internal/FulfilledPromise.php(47): React\Promise\Promise::React\Promise\{closure}(NULL)
#17 /var/www/html/vendor/react/promise/src/Promise.php(177): React\Promise\Internal\FulfilledPromise->then(Object(Closure), Object(Closure))
#18 /var/www/html/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\Internal\FulfilledPromise))
#19 /var/www/html/vendor/react/promise/src/Promise.php(286): React\Promise\Promise->settle(Object(React\Promise\Internal\FulfilledPromise))
#20 /var/www/html/vendor/react/promise/src/Internal/FulfilledPromise.php(47): React\Promise\Promise::React\Promise\{closure}(NULL)
#21 /var/www/html/vendor/react/promise/src/Promise.php(177): React\Promise\Internal\FulfilledPromise->then(Object(Closure), Object(Closure))
#22 /var/www/html/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\Internal\FulfilledPromise))
#23 /var/www/html/vendor/react/promise/src/Promise.php(286): React\Promise\Promise->settle(Object(React\Promise\Internal\FulfilledPromise))
#24 /var/www/html/vendor/react/promise/src/Internal/FulfilledPromise.php(47): React\Promise\Promise::React\Promise\{closure}(NULL)
#25 /var/www/html/vendor/react/promise/src/Promise.php(180): React\Promise\Internal\FulfilledPromise->then(Object(Closure), Object(Closure))
#26 /var/www/html/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\Internal\FulfilledPromise))
#27 /var/www/html/vendor/react/promise/src/Promise.php(286): React\Promise\Promise->settle(Object(React\Promise\Internal\FulfilledPromise))
#28 /var/www/html/vendor/react/promise/src/Internal/FulfilledPromise.php(47): React\Promise\Promise::React\Promise\{closure}(true)
#29 /var/www/html/vendor/react/promise/src/Promise.php(180): React\Promise\Internal\FulfilledPromise->then(Object(Closure), Object(Closure))
#30 /var/www/html/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\Internal\FulfilledPromise))
#31 /var/www/html/vendor/react/promise/src/Promise.php(286): React\Promise\Promise->settle(Object(React\Promise\Internal\FulfilledPromise))
#32 /var/www/html/vendor/react/promise/src/Internal/FulfilledPromise.php(47): React\Promise\Promise::React\Promise\{closure}(Object(Symfony\Component\Process\Process))
#33 /var/www/html/vendor/react/promise/src/Promise.php(180): React\Promise\Internal\FulfilledPromise->then(Object(Closure), Object(Closure))
#34 /var/www/html/vendor/react/promise/src/Promise.php(221): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\Internal\FulfilledPromise))
#35 /var/www/html/vendor/react/promise/src/Promise.php(286): React\Promise\Promise->settle(Object(React\Promise\Internal\FulfilledPromise))
#36 [internal function]: React\Promise\Promise::React\Promise\{closure}(Object(Symfony\Component\Process\Process))
#37 /var/www/html/vendor/composer/composer/src/Composer/Util/ProcessExecutor.php(328): call_user_func(Object(Closure), Object(Symfony\Component\Process\Process))
#38 /var/www/html/vendor/composer/composer/src/Composer/Util/Loop.php(90): Composer\Util\ProcessExecutor->countActiveJobs()
#39 /var/www/html/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(430): Composer\Util\Loop->wait(Array, NULL)
#40 /var/www/html/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(405): Composer\Installer\InstallationManager->waitOnPromises(Array)
#41 /var/www/html/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(319): Composer\Installer\InstallationManager->executeBatch(Object(Composer\Repository\InstalledFilesystemRepository), Array, Array, true, true, Array)
#42 /var/www/html/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(218): Composer\Installer\InstallationManager->downloadAndExecuteBatch(Object(Composer\Repository\InstalledFilesystemRepository), Array, Array, true, true, false, Array)
#43 /var/www/html/vendor/composer/composer/src/Composer/Installer.php(827): Composer\Installer\InstallationManager->execute(Object(Composer\Repository\InstalledFilesystemRepository), Array, true, true, false)
#44 /var/www/html/vendor/composer/composer/src/Composer/Installer.php(652): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), true)
#45 /var/www/html/vendor/composer/composer/src/Composer/Installer.php(298): Composer\Installer->doUpdate(Object(Composer\Repository\InstalledFilesystemRepository), true)
#46 /var/www/html/vendor/october/rain/src/Composer/Manager.php(93): Composer\Installer->run()
#47 /var/www/html/install_files/php/Installer.php(216): October\Rain\Composer\Manager->require(Array)
#48 /var/www/html/install_files/php/InstallerHandlers.php(187): Installer->runComposerInstall()
#49 /var/www/html/install_files/php/Installer.php(47): Installer->onInstallStep()
#50 /var/www/html/install_files/php/boot.php(87): Installer->__construct()
#51 /var/www/html/install.php(1): include('/var/www/html/i...')
#52 {main}
)
`

**Comment by daftspunk** [comment]
Looks like this was a temporary issue. Hopefully should be resolved now.

Reference: https://talk.octobercms.com/t/problem-installing-latest-october-cms/2913/9
