### ISSUE TITLE
Installation behind HTTP proxy (inc. authentication)

### ISSUE THREAD

**Issue by taviroquai** [octobercms/install#41]
Basically, this issue is to request changes to allow installation behind an HTTP proxy (inc. authentication).

Quick fix was to add PROXY params to cURL (method prepareServerRequest).

Example:

        // Add proxy params
        curl_setopt($curl, CURLOPT_PROXYTYPE, 'HTTP');
        curl_setopt($curl, CURLOPT_PROXY, 'proxy:8080');
        curl_setopt($curl, CURLOPT_PROXYUSERPWD, 'user:password');

**Comment by Shuunen** [comment]
thx @taviroquai , works nice

**Comment by daftspunk** [comment]
Relates to #27

**Comment by daftspunk** [comment]
If this is still an issue, please log it in the main October repo.
