### ISSUE TITLE
Allow for sqlsrv driver support

### ISSUE THREAD

**Issue by ejrebirth** [octobercms/install#63]
IIS PHP installations of 5.3 and above [do not include](http://php.net/manual/en/ref.pdo-dblib.php) the PDO dblib driver to connect to MSSQL and are advised to now use the Windows driver [SQLSRV](https://msdn.microsoft.com/en-us/sqlserver/ff657782.aspx?f=255&MSPPError=-2147217396).

**Comment by daftspunk** [comment]
Not sure what needs to happen here. The driver usage is governed by Laravel. If it is not supported by Laravel, then it's unsupported.

Closing as unactionable
