### ISSUE TITLE
Build 242. Exception after backend language change

### ISSUE THREAD

**Issue by romanov-acc** [octobercms/install#65]
Argument 1 passed to October\Rain\Translation\FileLoader::loadNamespaceOverrides() must be of the type array, integer given, called in ......../vendor/october/rain/src/Translation/FileLoader.php on line 72 and defined

**Comment by daftspunk** [comment]
Which language are you switching to?

**Comment by romanov-acc** [comment]
I switch english -> russian.  
If remove the strong typing on `FileLoader::loadNamespaceOverrides()` , error disappears.  
Sorry for my English.

**Comment by daftspunk** [comment]
I wasn't able to replicate this. What build are you running?

**Comment by romanov-acc** [comment]
Oh sorry. The problem lay in one of the third-party plugins. After his trip everything was fine.
