### ISSUE TITLE
blank page on production server, no error log

### ISSUE THREAD

**Issue by achtan** [octobercms/install#66]
Hi I see just blank page on production server, and my /storage/logs folder is empty

how can i see some errors or so ?

thx

ps: installation check on server was all OK

**Comment by daftspunk** [comment]
Can you check the PHP error log or apache log for clues? Also do other PHP files execute correctly?

**Comment by achtan** [comment]
on server i didn't have set APP_ENV variable. Anyhow is strange that i got only blank page...
