### ISSUE TITLE
sqlserver/IIS support abysmal. had to hack the installer.

### ISSUE THREAD

**Issue by tschallacka** [octobercms/install#69]
I had to modify the database query string in the installer.

A pdo_sqlsrv driver query string looks like this:

sqlsrv:Server=127.0.0.1;Database=DBNAME","username","password"

This is in /install_files/php/Installer.php line 157

     $dsn = 'sqlsrv:Server='.$host.(empty($port) ? '':','.$_port).$_name;

That is what works for pdo sqlsrv

In the exception message if the type is SQL server add a warning that might want to try to add \SQLEXPRESS behind the server name.

it doesn't use dlib as it was set up. Please modify your installer accordingly.
Also show tables does not work on sqlserver... that's mysql, please use SELECT * FROM INFORMATION_SCHEMA.TABLES

add at line 176
  

    elseif ($type === 'sqlsrv') {
        	$fetch = $db->query("SELECT * FROM INFORMATION_SCHEMA.TABLES", PDO::FETCH_NUM);
        }

Next up... there are no rewrite rules for IIS. only apache. Please add a checkbox or a check if it's installing on IIS or apache and supply the appropriate rewrite rules.

I'll post here whatever I hack togeter to make it working :-)

**Comment by tschallacka** [comment]
After some hacking and swearing at iis

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
 <rewrite>
        <rules>
            <rule name="redirect all requests" stopProcessing="true">
                <match url="^(.*)$" ignoreCase="false" />
                <conditions logicalGrouping="MatchAll">
                    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" pattern="" ignoreCase="false" />
                </conditions>
                <action type="Rewrite" url="index.php" appendQueryString="true" />
            </rule>
        </rules>
    </rewrite>
    </system.webServer>
</configuration>

**Comment by tschallacka** [comment]
In \modules\backend\widgets\Lists.php on line 429

                $joinSql = $this->isColumnRelated($column, true)
                    ? /*DbDongle::raw("group_concat(" . $sqlSelect . " separator ', ')")*/DbDongle::raw("" . $sqlSelect . " + ', '")
                    : DbDongle::raw($sqlSelect);

**Comment by tschallacka** [comment]
\vendor\october\rain\src\Database\Dongle.php 145

if(this->driver === 'sqlsrv') {
return str_ireplace('isnull(', 'coalesce(', $sql);
}

**Comment by tschallacka** [comment]
\vendor\october\rain\src\Databse\Relations\DeferOneOrmany.php

->whereRaw(DbDongle::parse('id > isnull((select max(id) from '.DbDongle::getTablePrefix().'deferred_bindings where

ifnull doesn't exist in sqlserver, isnull does.

Also, why not use the check from Dongle here?

**Comment by tschallacka** [comment]
\vender\october\rain\src\Database\Relations\DeferOneOrMany.php

line 40

$query->select('*')->from('deferred_bindings')

Line 51

 $query->select('*')->from('deferred_bindings')

**Comment by tschallacka** [comment]
in MediaManager.php line 978 

File::get(/*$uploadedFile->getRealPath()*/$uploadedFile->getPath().'\\'.$uploadedFile->getFileName())

For some reason getRealPath returns false, but patching up the string like this works fine.

**Comment by tschallacka** [comment]
File.php in \vendor\october\rain\src\Database\Attach\File.php

Line 86
$realpath = (empty(trim($uploadedFile->getRealPath())) ? $uploadedFile->getPath().'\\'.$uploadedFile->getFileName() : $uploadedFile->getRealPath());
        $this->putFile($realpath, $this->disk_name);

Line 106
$realpath = (empty(trim($uploadedFile->getRealPath())) ? $uploadedFile->getPath().'\\'.$uploadedFile->getFileName() : $uploadedFile->getRealPath());
        $this->putFile($realpath, $this->disk_name);

**Comment by tschallacka** [comment]
When the installer calls the actual config for connecting to the server with the laravel install, it has inserted the port into the configuration file, even if you left this empty in the setup. 

but when you make this field empty in the config the connection string is invalid because of the surplus ,

I patched it by adding 

     $dsn = str_replace('SQLEXPRESS,;','SQLEXPRESS;',$dsn);

in /vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php on line 47

less than ideal, but it works.

**Comment by daftspunk** [comment]
If this is still an issue, please log it in the main October repo.
