### ISSUE TITLE
Packages are not downloaded completely

### ISSUE THREAD

**Issue by osiloke** [octobercms/install#72]
I'm trying to install october cms on a cpanel shared account. The logs suggest that the cms package is not downloaded completely. I've set all folder permissions to 777. Please take a look at the log below.
Also, where is the install app trying to download the file to. I don't see any files in install_files/temp
.============================ POST REQUEST ==========================.
[2015/08/28 12:31:18] Postback payload: Array
(
    [step] => downloadCore
    [meta] => Array
        (
            [core] => Array
                (
                    [hash] => 982441cd5da8929a6257ee771ea8b6da
                    [build] => 292
                    [uhash] => 6a4f1564f29f93ecf8b4a8a5dcf2da57
                )

        )

    [handler] => onInstallStep
)

[2015/08/28 12:31:18] Install step: downloadCore
[2015/08/28 12:31:20] File hash mismatch: 982441cd5da8929a6257ee771ea8b6da (expected) vs 62780767f36e1c137d44ec33b036c13a (actual)
[2015/08/28 12:31:20] Local file size: 7974912
[2015/08/28 12:31:20] Handler error (onInstallStep): Package files from server are corrupt
[2015/08/28 12:31:20] Trace log:
#0 /home/niss/public_html/install-master/install_files/php/Installer.php(299): Installer->requestServerFile('core', '982441cd5da8929...', 'core/get', Array)
#1 /home/niss/public_html/install-master/install_files/php/Installer.php(48): Installer->onInstallStep()
#2 /home/niss/public_html/install-master/install_files/php/boot.php(74): Installer->__construct()
#3 /home/niss/public_html/install-master/install.php(1): include('/home/niss/publ...')
#4 {main}

**Comment by daftspunk** [comment]
If this is still an issue, please log it in the main October repo.
