### ISSUE TITLE
Adding new theme error

### ISSUE THREAD

**Issue by MkBeeCtrl** [octobercms/install#79]
Hello, 

I've installed october using ftp, just uploaded the installation files and performed the installation.

I logged in successfully and tried to add blank new theme, only loading gif appears after this and Chrome console returns the following:

    http://dev.beectrl.com/backend/cms/modules/cms/widgets/mediamanager/assets/js/mediamanager-browser-min.js?v313 Failed to load resource: the server responded with a status of 404 (OK)
      http://dev.beectrl.com/backend/cms/modules/cms/widgets/mediamanager/assets/css/mediamanager.css?v313 Failed to load resource: the server responded with a status of 404 (OK)
    http://dev.beectrl.com/backend/cms/modules/backend/widgets/form/assets/js/october.form.js?v313 Failed to load resource: the server responded with a status of 404 (OK)
    

    http://dev.beectrl.com/backend/cms/modules/cms/widgets/mediamanager/assets/css/mediamanager.css?v313 Failed to load resource: the server responded with a status of 404 (OK)

I did look manually for the missing files and the "cms" folder under the "backend" is missing.

Tried to install october two times, used package from github and from your official page.

**Comment by daftspunk** [comment]
This looks like a web server configuration issue, see the documentation. If this is still an issue, please log it in the main October repo.
