### ISSUE TITLE
SQLite | PDO vs SQLite3

### ISSUE THREAD

**Issue by TigersWay** [octobercms/install#83]
Hi,

At the end of Installer.php - function validateSqliteFile($filename), nothing has been done to check if the module/class SQLite3 is really installed.
Maybe you should replace
`new SQLite3($filename);`
by
`new PDO('sqlite:'.basename($filename));`
which seems to be working perfectly.

Thanks

**Comment by daftspunk** [comment]
Why is calling `basename()` on the `$filename` necessary?

**Comment by TigersWay** [comment]
Upss  no, it's a mistake... more exactly something left from my own tests to be sure opening the connection was enough.
`new PDO('sqlite:'.$filename);`
should be enough.
